name: Publish Site

on:
  push:
    branches:
      - master

jobs:
  publish-site:
    runs-on: ubuntu-latest
    steps:
      - name: Refresh
        run: git clone https://github.com/${{ secrets.ACTIONS_ORG }}/${{ secrets.ACTIONS_REPO }} . && git submodule foreach git pull origin master && git remote add origin https://${{ secrets.ACTIONS_USERNAME }}:${{ secrets.ACTIONS_SECRET }}@github.com/${{ secrets.ACTIONS_ORG }}/${{ secrets.ACTIONS_REPO }}.git && git commit -am "Refresh triggered by ${{ github.repository }}" && git push origin master