name: Publish Site

on:
  push:
    branches:
      - master

jobs:
  publish-site:
    runs-on: ubuntu-latest
    steps:
      - name: Init
        run: git init .

      - name: Login
        run: git remote add origin https://${{ secrets.ACTIONS_USERNAME }}:${{ secrets.ACTIONS_SECRET }}@github.com/${{ secrets.ACTIONS_ORG }}/${{ secrets.ACTIONS_REPO }}.git

      - name: Pull
        run: git pull origin main

      - name: Refresh
        run: git submodule foreach git pull origin master && git commit -am "Refresh triggered by ${{ github.repository }}" && git push origin main

      - name: Commit
        run: git commit -am "Refresh triggered by ${{ github.repository }}"

      - name: Push
        run: git push origin main
